### ISSUE TITLE
Getting rid of MultiInv, switch back to MV-Inv

### ISSUE THREAD

**Issue by TNTUP** [AddstarMC/Multiverse-Inventories#3]
Hi, im currently using MultiInv and inventory/enderchest issues is happening too many times, alot of players complains that they keep losing their inventory, idk how it happens, sometimes it swaps, dupes, and I can't do much anything, obligated to keep it due to Creative, Skyblock, AcidIsland and Minigames.

I hope your fork of MV-Inv with UUID can offer a converter (MultiInv to MV-Inv) and no inventory/enderchest loss, swapping between worlds, duping items and mysql support (I guess MV-Inv doesn't support mysql).

MultiInv is UUID-Aware and your fork will be, that I hope if its possible because this (censored) plugin drives me nuts...

**Comment by addstar** [comment]
Hello,
I haven't experienced the Enderchest issues myself and we have a reasonable sized player base with thousands of enderchests in use. I'm not aware of any complaints but this could be specific to your set up or the configuration you use. It also could be interference from another plugin.

Which version of MVInv are you using? If you are able to detail how to reproduce the bug, I can test/fix it, but without further information there's nothing I can do, sorry.

As for the converter, there is some information in the [README.md](https://github.com/addstar/Multiverse-Inventories/blob/master/README.md) (added in ef8ffd6d2e74675243a37389f272a085f2a9a5bf)  which links to a converter and some instructions of how to use it.

**Comment by TNTUP** [comment]
Hey, well it could be, but I not sure which one is causing it or its MultiInv itself. The version im use is a dev build, MultiInv 3.3.2-dev.

About the converter, its not a name-to-uuid conversion, I mean converting MultiInv (im using mysql) to Multiverse-Inventories. Thanks anyway if you couldn't make a converter. :)

**Comment by addstar** [comment]
Err.. my apologies.. I completely misread your issue. I thought you said you were on Multiverse-Inv :flushed: 

Unfortunately, I don't have the time to build you a converter but someone is likely to have already made one. I'm sure many people have switched MultiInv <-> MVInv before. Try searching the spigot/bukkit forums or google. Sorry about that.

**Comment by addstar** [comment]
Also, if your search for an existing converter fails, you could ask on the Spigotmc forums for some developer to write one for you? I'm sure it wouldn't take much to do.

**Comment by TNTUP** [comment]
Yeah, well thanks for your time viewing meh ticket though, have a nice day ;)
